In [1]:
import numpy as np

1. Array Creation 
    create numpy array via 1D list
    

In [67]:
list1 = [1,2,4,5, 'adi']

arr1 = np.array(list1)
print(arr1)
print(type(arr1))

['1' '2' '4' '5' 'adi']
<class 'numpy.ndarray'>


2. Array Creation 
    create numpy array via 2D list
    set  explicitly data type to float32
    

In [5]:
lsit2 = [
    [1,2,3],
    [6,4,5]
]

arr2 = np.array(lsit2, dtype='float32')
print(arr2)
print(type(arr2))

[[1. 2. 3.]
 [6. 4. 5.]]
<class 'numpy.ndarray'>


In [11]:
np.zeros((3,5), dtype='int')
np.zeros(10, dtype='int')


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones((3,5), dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [20]:
np.arange(0,20,2)  
#we used this in for loop as for i in range(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [35]:
np.random.random()

0.9055389872604921

In [32]:
np.random.normal(0,1, (3,3))

array([[ 1.01586759, -1.00417578,  0.57441817],
       [-0.55960951,  2.71463516, -1.68494085],
       [ 0.50316347,  0.15721647,  1.28680079]])

In [38]:
np.random.randint(0,20, (3,3))

array([[ 6,  0,  3],
       [ 5,  7, 17],
       [13, 11, 12]])

In [40]:
list3 = [1,2,3,4,5,6,7]

arr3 = np.array(list3)
print(arr3)

[1 2 3 4 5 6 7]


In [52]:
sample_array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])
print(sample_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
print(f'The dimesnion is : {sample_array.ndim}')
print(f'The shape of array  is : {sample_array.shape}')
print(f'The size of array  is : {sample_array.size}')
print(f'The data type is : {sample_array.dtype}')
print(f'The item size is : {sample_array.itemsize}')


The dimesnion is : 2
The shape of array  is : (3, 3)
The size of array  is : 9
The data type is : int64
The item size is : 8
