In [3]:
import numpy as np

1. Array Creation 
    create numpy array via 1D list
    

In [4]:
list1 = [1,2,4,5, 'adi']

arr1 = np.array(list1)
print(arr1)
print(type(arr1))

['1' '2' '4' '5' 'adi']
<class 'numpy.ndarray'>


2. Array Creation 
    create numpy array via 2D list
    set  explicitly data type to float32
    

In [5]:
lsit2 = [
    [1,2,3],
    [6,4,5]
]

arr2 = np.array(lsit2, dtype='float32')
print(arr2)
print(type(arr2))

[[1. 2. 3.]
 [6. 4. 5.]]
<class 'numpy.ndarray'>


In [6]:
np.zeros((3,5), dtype='int')
np.zeros(10, dtype='int')


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((3,5), dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
np.arange(0,20,2)  
#we used this in for loop as for i in range(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.random.random()

0.31710045693986644

In [11]:
np.random.normal(0,1, (3,3))

array([[ 0.82739397,  0.00430578,  0.74905818],
       [-0.8901506 ,  0.59000404,  0.44655639],
       [ 0.29005584, -0.40391549,  1.04227252]])

In [12]:
np.random.randint(0,20, (3,3))

array([[15, 14,  8],
       [10, 16, 11],
       [ 7,  3, 17]])

In [13]:
list3 = [1,2,3,4,5,6,7]

arr3 = np.array(list3)
print(arr3)

[1 2 3 4 5 6 7]


In [14]:
sample_array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])
print(sample_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
print(f'The dimesnion is : {sample_array.ndim}')
print(f'The shape of array  is : {sample_array.shape}')
print(f'The size of array  is : {sample_array.size}')
print(f'The data type is : {sample_array.dtype}')
print(f'The item size is : {sample_array.itemsize}')


The dimesnion is : 2
The shape of array  is : (3, 3)
The size of array  is : 9
The data type is : int64
The item size is : 8


In [20]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
np.reshape(arr,(4,3))


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
#reshaping in 3D
arr.reshape((2,3,2)) 

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

Q. can we reshape to any shape?
    yes, as long as element required for reshaping are equal in both shapes.

In [30]:
#convert 1d array with 8 elements to a 2D array with shape (3,3)

arr3 = np.array([1,2,3,4,5,6,7,8])

arr3.reshape((3,3))

ValueError: cannot reshape array of size 8 into shape (3,3)

- This process raise an exception, since there are 8 elements before reshapping and 9 elements after reshapping
- For reshapping to happen, number of elements before reshapping should be equal to number of elements afer reshaping.


#Joinin Arrays
    Array joining meand putting content of two  or more array in  a single array.

Two types:
    1. Concatenation
    2. Stacking

1. Concatenation
    we pass sequence of array that we want to the concatenate() function.
    
    syntax:
        np.concatentation ((a1,a2, ...), axis=0, out=None)

        a1,a2 are sequnece of array _like. They must have same shape
        axis int, optional axis along which array will be concatenated
        out ndarray 

In [40]:
arr1 = np.array([1,1,1,1])
arr2 = np.array([2,2,2,2])

concat_arr = np.concatenate((arr1,arr2), axis=0)
concat_arr

array([1, 1, 1, 1, 2, 2, 2, 2])

In [38]:
a = np.array([
            [1,1,1],
            [1,1,1]
            ])

b = np.array([
            [9,9,9],
            [9,9,9]
])

concat_arr = np.concatenate((a,b), axis=1)
concat_arr

array([[1, 1, 1, 9, 9, 9],
       [1, 1, 1, 9, 9, 9]])

#spliting arrays
 - splitting is reverse operation of joining
 - joining mereges multiple arrays into one
 - splitting breaks one array into multiple one
 - can be implemented using numpy functions

 syntax:
    - numpy.split()
    - numpy.array_split()


- we pass aray we want to split and the number of split 
- sub-arrays obtained after splitting is only view of the original arrays.
   changes made to the sub-arrays also reflect into original arrays
   

In [51]:
ar = [1,2,3,4,5,6]

arr = np.array(ar)

arr

spit = np.split(arr,4)



ValueError: array split does not result in an equal division

In [55]:
spit = np.array_split(arr,4)
spit

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [56]:

#splitting 2D array

a = np.array([
            [1,1,1],
            [1,1,1],
            [9,9,9],
            [9,9,9]
 ])


np.array_split(a,4)

[array([[1, 1, 1]]),
 array([[1, 1, 1]]),
 array([[9, 9, 9]]),
 array([[9, 9, 9]])]

In [59]:

#splitting 2D array

a = np.array([
            [1,1,1],
            [1,1,1],
            [9,9,9],
            [9,9,9]
 ])


np.array_split(a,4, axis=1)

[array([[1],
        [1],
        [9],
        [9]]),
 array([[1],
        [1],
        [9],
        [9]]),
 array([[1],
        [1],
        [9],
        [9]]),
 array([], shape=(4, 0), dtype=int64)]

Numpy Universal Function (Ufuncs)
- Looping over the array to perform repeated task like addition, subtraction etc on each array element are common
- computation time to perform such repeated task increases with relatively larger data
- Numpy makes this faster by using vectorized opertaions, implemented through ufuncs.
- Types:
    - Uniary
    - Binary 

In [63]:
import time

x1 = np.arange(1,100000)
x2 = np.arange(1,100000)
mul = np.zeros(x1.shape)
start_time = time.process_time()

for i in range(len(x1)):
    mul[i] = x1[i] * x2[i]

print(mul)
end_time = time.process_time()

print(end_time - start_time)

[1.00000000e+00 4.00000000e+00 9.00000000e+00 ... 9.99940001e+09
 9.99960000e+09 9.99980000e+09]
0.11300263399999988


In [67]:
a = np.array([1,2,3])
b = np.array([[10],[20],[30]])

print(f'shape of {a}')
print(f'shape of {b}')

print(a+b)

shape of [1 2 3]
shape of [[10]
 [20]
 [30]]
[[11 12 13]
 [21 22 23]
 [31 32 33]]
